version: '3.4'
services:
  ea_api:
    image: ea_api
    container_name: eaapi
    build:
      context: .
      dockerfile: ProductAPI/Dockerfile
    restart: on-failure      
    ports:
      - 5001:8001
    depends_on:
      - db
    networks:
      - ea_network

  ea_webapp:
    image: ea_webapp
    container_name: eawebapp
    build:
      context: .
      dockerfile: EAWebApp/Dockerfile
    restart: on-failure      
    ports:
      - 5002:8000
    depends_on: 
      - ea_api
    networks: 
      - ea_network
  db:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      SA_PASSWORD: "Password%1#29"
      ACCEPT_EULA: "1"
      name: azuresqledge
    container_name: sqlserver
    hostname: sqlserver
    ports:
      - 1433:1433
    networks:
      - ea_network

  ea_test:
    image: ea_atest
    container_name: ea_test
    build:
      context: .
      dockerfile: TestBdd/Dockerfile     
    depends_on:
      - ea_api
      - selenium-hub
    environment:
      - ASPNETCORE_ENVIRONMENT=remote
    networks:
      - ea_network
  node-docker:
      image: seleniarm/node-chromium:latest
      shm_size: 2gb
      volumes:
        - ./assets:/opt/selenium/assets
      depends_on:
        - selenium-hub
      environment:
        - SE_EVENT_BUS_HOST=selenium-hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      networks:
        - ea_network

  selenium-hub:
    image: seleniarm/hub:4.7.2-20221219
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - ea_network
networks: 
   ea_network:
