name: Docker Image CI

on:
  push:
    branches: [ "specflow" ]
  pull_request:
    branches: [ "specflow" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Runing the script file
      run: |
        echo --Running Test ---
        sh  ./scripts/run.sh
    - name: Publish the report as artifact 
      uses: actions/upload-artifact@v3
      with:
        name: specflow-report-artifact
        path: ./reports
